
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";


import { UserGuard } from "app";


const App = lazy(() => import("./pages/App.tsx"));
const ClassDetails = lazy(() => import("./pages/ClassDetails.tsx"));
const CourseHistory = lazy(() => import("./pages/CourseHistory.tsx"));
const Dashboard = lazy(() => import("./pages/Dashboard.tsx"));
const LessonEditor = lazy(() => import("./pages/LessonEditor.tsx"));
const LessonView = lazy(() => import("./pages/LessonView.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const Register = lazy(() => import("./pages/Register.tsx"));
const ResetPassword = lazy(() => import("./pages/ResetPassword.tsx"));
const StudentDashboard = lazy(() => import("./pages/StudentDashboard.tsx"));
const TeacherClassDetails = lazy(() => import("./pages/TeacherClassDetails.tsx"));
const TeacherDashboard = lazy(() => import("./pages/TeacherDashboard.tsx"));
const Unauthorized = lazy(() => import("./pages/Unauthorized.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/class-details", element: <UserGuard><ClassDetails /></UserGuard>},
	{ path: "/classdetails", element: <UserGuard><ClassDetails /></UserGuard>},
	{ path: "/course-history", element: <UserGuard><CourseHistory /></UserGuard>},
	{ path: "/coursehistory", element: <UserGuard><CourseHistory /></UserGuard>},
	{ path: "/dashboard", element: <UserGuard><Dashboard /></UserGuard>},
	{ path: "/lesson-editor", element: <UserGuard><LessonEditor /></UserGuard>},
	{ path: "/lessoneditor", element: <UserGuard><LessonEditor /></UserGuard>},
	{ path: "/lesson-view", element: <UserGuard><LessonView /></UserGuard>},
	{ path: "/lessonview", element: <UserGuard><LessonView /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/register", element: <UserGuard><Register /></UserGuard>},
	{ path: "/reset-password", element: <UserGuard><ResetPassword /></UserGuard>},
	{ path: "/resetpassword", element: <UserGuard><ResetPassword /></UserGuard>},
	{ path: "/student-dashboard", element: <UserGuard><StudentDashboard /></UserGuard>},
	{ path: "/studentdashboard", element: <UserGuard><StudentDashboard /></UserGuard>},
	{ path: "/teacher-class-details", element: <UserGuard><TeacherClassDetails /></UserGuard>},
	{ path: "/teacherclassdetails", element: <UserGuard><TeacherClassDetails /></UserGuard>},
	{ path: "/teacher-dashboard", element: <UserGuard><TeacherDashboard /></UserGuard>},
	{ path: "/teacherdashboard", element: <UserGuard><TeacherDashboard /></UserGuard>},
	{ path: "/unauthorized", element: <UserGuard><Unauthorized /></UserGuard>},

];
